### ISSUE TITLE
Media Player Entity won't show up. 

### ISSUE THREAD

**Issue by codecs02-marcher** [smartHomeHub/SmartIR#1262]
**Home Assistant version**
12.3
**SmartIR version**
1.17.9
**SmartIR configuration**
esphome:
  name: humidifier_esp01
  platform: ESP8266
  board: esp01_1m
api:
  encryption:
    key: !secret api_key
  services:
    - service: send_raw_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return command;'

ota:
  password: !secret ota_key

remote_transmitter:
  pin: GPIO2
  carrier_duty_percent: 50%

```configuration.yaml
media_player: !include mediaplayer.yaml
smartir:
  check_updates: false
Add configuration here
```mediaplayer.yaml
- platform: smartir
  name: ESP TV
  unique_id: esp_tv
  device_code: 1380
  controller_data: humidifier_esp01_send_raw_command
  power_sensor: binary_sensor.smartir_tv

**Describe the bug**

SmartIR media player entity won't show up. Climate Entity of smartir works just fine.
I tried several restart. updated SmartIR but nothing seems to work.

**Debug log**

```text

Add your logs here.

```2024-06-09 19:12:58.929 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-09 19:12:58.932 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration switch_humidifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-09 19:12:58.935 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration whatsapp which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-09 19:12:58.937 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration rpi_gpio which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-09 19:12:58.940 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration extended_openai_conversation which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-09 19:12:58.943 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration simpleicons which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-09 19:12:58.946 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration fontawesome which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-09 19:12:58.949 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration cupertino which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-09 19:12:58.951 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartir which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-09 19:12:58.954 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-09 19:12:58.956 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-09 19:12:58.958 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration rpi_gpio_pwm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-09 19:13:03.022 WARNING (ImportExecutor_0) [homeassistant.components.humidifier] DEVICE_CLASS_DEHUMIDIFIER was used from switch_humidifier, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierDeviceClass.DEHUMIDIFIER instead, please report it to the author of the 'switch_humidifier' custom integration
2024-06-09 19:13:03.027 WARNING (ImportExecutor_0) [homeassistant.components.humidifier] DEVICE_CLASS_HUMIDIFIER was used from switch_humidifier, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierDeviceClass.HUMIDIFIER instead, please report it to the author of the 'switch_humidifier' custom integration
2024-06-09 19:13:03.032 WARNING (ImportExecutor_0) [homeassistant.components.humidifier] SUPPORT_MODES was used from switch_humidifier, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierEntityFeature.MODES instead, please report it to the author of the 'switch_humidifier' custom integration
2024-06-09 19:13:03.039 WARNING (ImportExecutor_0) [homeassistant.components.humidifier] DEVICE_CLASS_DEHUMIDIFIER was used from switch_humidifier, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierDeviceClass.DEHUMIDIFIER instead, please report it to the author of the 'switch_humidifier' custom integration
2024-06-09 19:13:03.045 WARNING (ImportExecutor_0) [homeassistant.components.humidifier] DEVICE_CLASS_HUMIDIFIER was used from switch_humidifier, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierDeviceClass.HUMIDIFIER instead, please report it to the author of the 'switch_humidifier' custom integration
2024-06-09 19:13:03.050 WARNING (ImportExecutor_0) [homeassistant.components.humidifier] SUPPORT_MODES was used from switch_humidifier, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierEntityFeature.MODES instead, please report it to the author of the 'switch_humidifier' custom integration
2024-06-09 19:13:03.352 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5. Please report this issue.
Stack (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 220, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 208, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 63, in run_callback
future.set_result(callback(*args))
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 212, in async_track_state_change
frame.report(
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 154, in report
_LOGGER.warning(msg, stack_info=True)
2024-06-09 19:13:03.738 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_OFF was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'smartir' custom integration
2024-06-09 19:13:03.743 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_HEAT was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'smartir' custom integration
2024-06-09 19:13:03.749 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_COOL was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please report it to the author of the 'smartir' custom integration
2024-06-09 19:13:03.754 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_DRY was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.DRY instead, please report it to the author of the 'smartir' custom integration
2024-06-09 19:13:03.760 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_FAN_ONLY was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.FAN_ONLY instead, please report it to the author of the 'smartir' custom integration
2024-06-09 19:13:03.767 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_AUTO was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.AUTO instead, please report it to the author of the 'smartir' custom integration
2024-06-09 19:13:03.773 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'smartir' custom integration
2024-06-09 19:13:03.781 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_FAN_MODE was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'smartir' custom integration
2024-06-09 19:13:03.787 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_SWING_MODE was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please report it to the author of the 'smartir' custom integration
2024-06-09 19:13:03.896 ERROR (MainThread) [custom_components.smartir.media_player] The device JSON file is invalid
2024-06-09 19:13:03.902 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|FAN_MODE|SWING_MODE: 41>, please report it to the author of the 'smartir' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-06-09 19:13:03.903 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.smartir.climate.SmartIRClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please report it to the author of the 'smartir' custom integration
2024-06-09 19:13:03.905 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.smartir.climate.SmartIRClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please report it to the author of the 'smartir' custom integration
2024-06-09 19:13:03.905 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.smartir.climate.SmartIRClimate'>) implements HVACMode(s): off, cool, dry, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please report it to the author of the 'smartir' custom integration
2024-06-09 19:13:03.917 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'smartir' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/smartir/climate.py, line 175: async_track_state_change(self.hass, self._temperature_sensor,, please report it to the author of the 'smartir' custom integration
2024-06-09 19:13:03.923 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'smartir' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/smartir/climate.py, line 183: async_track_state_change(self.hass, self._humidity_sensor,, please report it to the author of the 'smartir' custom integration
2024-06-09 19:13:06.947 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.0.200 for adguard
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/adguard/__init__.py", line 70, in async_setup_entry
version = await adguard.version()
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/adguardhome/adguardhome.py", line 232, in version
response = await self.request("status")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/adguardhome/adguardhome.py", line 171, in request
raise AdGuardHomeError(
adguardhome.exceptions.AdGuardHomeError: (401, {'message': '<html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body>\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'})
2024-06-09 19:13:09.312 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-06-09 19:13:10.196 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/switch_humidifier/humidifier.py", line 208, in _state_changed
if not new_state is None and not new_state.state == 'unknown' and not new_state.state == 'unavailable' and not old_state.state == new_state.state:
^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'
2024-06-09 19:13:24.327 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

Logger: custom_components.smartir.media_player
Source: custom_components/smartir/media_player.py:79
integration: SmartIR ([documentation](https://github.com/smartHomeHub/SmartIR))
First occurred: 6:43:03 AM (1 occurrences)
Last logged: 6:43:03 AM

The device JSON file is invalid

Add any other context about the problem here.

**Comment by vassilis-panos** [comment]
As the error logs show, the device JSON file is invalid
